### ISSUE TITLE
Error after installing the Vignettes.

### ISSUE THREAD

**Issue by spholmes** [krisrs1128/treelapse#155]
After installing the vignettes, I receive a warning that keeps coming back:

In get(Info[i, 1], envir = env) : internal error -3 in R_decompress1

**Comment by spholmes** [comment]
After reloading the R session this does not persist, so it is only minor, I was worried it was a major
issue, but everything now functions.
Strangely I tried all the reinstall on a different Mac (also Yosemite) same version of R
R version 3.3.2 (2016-10-31) and I did not get the error, so please ignore, I must have made a mistake.

**Comment by krisrs1128** [comment]
Okay, I'll keep an eye out for this though, if you ran into this I suspect others will too.
