### ISSUE TITLE
pregnancy.Rmd vignette, doi_sankey error

### ISSUE THREAD

**Issue by brooksomics** [krisrs1128/treelapse#183]
After running the `doi-sankey` chunk (line 75), I encounter this error:
```
Error in doi_sankey(values %>% group_by(group, unit) %>% dplyr::summarise(value = mean(value)),  : 
  unused argument (display_opts = list(focus_font_size = 20, font_size = 15, leaf_width = 37, leaf_height = 75))
```

Interesting tool. Excited to explore it more!

**Comment by krisrs1128** [comment]
Hi @brooksomics. Could you try reinstalling from the branch I just pushed (`devtools::install_github("krisrs1128/treelapse@style-to-doi")`), and then trying out that line again? I think I forgot to update the interface for that function.

Let me know if that fixes things, so I can merge the change. Thank you for trying out the package!

**Comment by krisrs1128** [comment]
Hi @brooksomics. Wanted to check whether you're still interested in trying this out, otherwise I'll merge the pull request and close this issue in the next few days.

**Comment by brooksomics** [comment]
Hi @krisrs1128. This did indeed work. The `pregnancy.Rmd` vignette is now working as I'd expect. Thanks (and sorry for the delayed reply)!

**Comment by krisrs1128** [comment]
Sounds good, thanks for trying it out!
